SEED = 1024
IN_CHANNEL = 3
OUT_CHANNEL = 3
NGF = 64
NDF = 64
DISCRIMINATOR_LAYER = 3
INPUT_SIZE = 256

# train
EPOCHS = 200
BATCH_SIZE = 16
TRAIN_NUM_WORKERS = 4
VAL_NUM_WORKERS = 2
TEST_NUM_WORKERS =2

G_LR = 2E-4
G_BETAS = (0.5, 0.999)
D_LR = 2E-4
D_BETAS = (0.5, 0.999)
LR_DECAY_EPOCHS = 30

PRINT_FREQUENT = 0.01
EVAL_FREQUENT = 0.1

REAL_LABEL = 1
FAKE_LABEL = 0

L1_LOSS_LAMUDA = 150
USING_DROPOUT_DURING_EVAL = False

# data
DATASET_ROOT = "D:/Users/peggy/Dataset/texture/texture"
DATASET = "texture"

# output
CONSTANT_FEATURE_DIS_LEN = 4
OUTPUT_ROOT = "./output"
OUTPUT_MODEL_KEY = "model"
OUTPUT_LOG_KEY = "logs"
OUTPUT_IMAGE_KEY = "images"
